Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,14 +30,14 @@ jobs:
           ssh-keyscan ${{ secrets.GITLAB_HOST }} >> ~/.ssh/known_hosts
 
       - name: Run Ansible playbook (17.0)
-        run: ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3"
-        continue-on-error: true
-
-      - name: Update playbook for 17.3
         run: |
-          sed -i 's/target_version: 17.0/target_version: 17.3/g' gitlab_upgrade.yml
-          # No need to modify version_check.sh, it's already in the repo
-
-      - name: Run Ansible playbook (17.3)
-        run: ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3"
-        continue-on-error: true
+          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3"
+          # Check if the upgrade was successful and proceed only if it was
+          if [[ $? -eq 0 ]]; then
+            echo "Upgrade to 17.0 successful. Proceeding to 17.3"
+            sed -i 's/target_version: 17.0/target_version: 17.3/g' gitlab_upgrade.yml
+            ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3"
+          else
+            echo "Upgrade to 17.0 failed. Exiting."
+            exit 1
+          fi
